apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace:  ingress
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: acrproep01.azurecr.io/ordersservice:v2.2
        ports:
        - containerPort: 80
